version: '3.8'

services:
  blockly-fe:
    build: .
    container_name: blockly-fe
    ports:
      - "8080:8080"
    environment:
      REACT_APP_API_URL: http://blockly-be:8000
    networks:
      - blockly-network

networks:
  blockly-network:
    external: true
