version: "2.19.1"

services:
  blockly-fe-clone:
    build: .
    container_name: blockly-fe-clone
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - blockly-network
    restart: always

networks:
  blockly-network:
    external: true
