version: '3.8'

services:
  blockly-fe:
    build: .
    container_name: blockly-fe
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=https://api.timothypham.io.vn
      - REACT_APP_FIREBASE_EMAIL=datpham@gmail.com
      - REACT_APP_FIREBASE_PASSWORD=datons2024
    networks:
      - blockly-network
    restart: always

networks:
  blockly-network:
    external: true
