# syntax=docker/dockerfile:1

FROM node:18.16.1-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

# Stage 2: Serve the built app with a simple server
FROM node:18.16.1-alpine
WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install -g serve
EXPOSE 8081
CMD ["serve", "-s", "build", "-l", "8081"]
